package akinator;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * Juan Casado Ballesteros
 * Gabriel López Cuenca
 * Álvaro Zamorano Ortega
 */
public class Interfaz extends javax.swing.JFrame {

    int port = 5009;
    DatagramSocket socket;
    InetAddress direccion = InetAddress.getLoopbackAddress();

    /**
     * Creates new form Interfaz
     */
    public Interfaz(DatagramSocket socket) {
        initComponents();
        this.socket = socket;
    }

    public void enviar(String datos) {
        byte[] sendData = datos.getBytes();
        DatagramPacket sendPacket = new DatagramPacket(sendData, sendData.length, direccion, port);

        try {
            socket.send(sendPacket);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void escribirPregunta(String pregunta) {
        CampoPreguntas.setText(pregunta);
    }

    public void escribirVarios(String varios) {
        CampoVarios.setText(varios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoPreguntas = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        CampoNuevoLenguaje = new javax.swing.JTextField();
        BotonResSI = new javax.swing.JButton();
        BotonResPSI = new javax.swing.JButton();
        BotonResNS = new javax.swing.JButton();
        BotonResPNO = new javax.swing.JButton();
        BotonResNO = new javax.swing.JButton();
        BotonInsertarLenguaje = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CampoVarios = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Akinator");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 255));
        setMinimumSize(new java.awt.Dimension(1045, 595));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoPreguntas.setEditable(false);
        CampoPreguntas.setFont(new java.awt.Font("Nirmala UI", 0, 10)); // NOI18N
        getContentPane().add(CampoPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 650, 30));

        jLabel22.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel22.setText("PREGUNTA");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 79, 47));

        jLabel23.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel23.setText("rESPUESTA");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        CampoNuevoLenguaje.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        getContentPane().add(CampoNuevoLenguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 136, 30));

        BotonResSI.setBackground(new java.awt.Color(255, 51, 51));
        BotonResSI.setFont(new java.awt.Font("Ravie", 0, 11)); // NOI18N
        BotonResSI.setText("SI");
        BotonResSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResSIActionPerformed(evt);
            }
        });
        getContentPane().add(BotonResSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 62, -1));

        BotonResPSI.setBackground(new java.awt.Color(255, 51, 51));
        BotonResPSI.setFont(new java.awt.Font("Ravie", 0, 11)); // NOI18N
        BotonResPSI.setText("PROBABLEMENTE SI");
        BotonResPSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResPSIActionPerformed(evt);
            }
        });
        getContentPane().add(BotonResPSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, -1));

        BotonResNS.setBackground(new java.awt.Color(255, 51, 51));
        BotonResNS.setFont(new java.awt.Font("Ravie", 0, 11)); // NOI18N
        BotonResNS.setText("NO SE");
        BotonResNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResNSActionPerformed(evt);
            }
        });
        getContentPane().add(BotonResNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        BotonResPNO.setBackground(new java.awt.Color(255, 51, 51));
        BotonResPNO.setFont(new java.awt.Font("Ravie", 0, 11)); // NOI18N
        BotonResPNO.setText("PROBABLEMENTE NO");
        BotonResPNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResPNOActionPerformed(evt);
            }
        });
        getContentPane().add(BotonResPNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        BotonResNO.setBackground(new java.awt.Color(255, 51, 51));
        BotonResNO.setFont(new java.awt.Font("Ravie", 0, 11)); // NOI18N
        BotonResNO.setText("NO");
        BotonResNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResNOActionPerformed(evt);
            }
        });
        getContentPane().add(BotonResNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        BotonInsertarLenguaje.setBackground(new java.awt.Color(0, 255, 51));
        BotonInsertarLenguaje.setFont(new java.awt.Font("Ravie", 0, 11)); // NOI18N
        BotonInsertarLenguaje.setText("CONFIRMAR");
        BotonInsertarLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsertarLenguajeActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInsertarLenguaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, -1, 30));

        jLabel28.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel28.setText("NUEVO LENGUAJE");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, 47));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        jLabel1.setText("LOPEZ CUENCA, GABRIEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, -1, 20));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        jLabel5.setText("ZAMORANO ORTEGA, ALVARO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 510, 150, 20));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        jLabel6.setText("CASADO BALLESTEROS, JUAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, -1, 20));

        CampoVarios.setEditable(false);
        CampoVarios.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        getContentPane().add(CampoVarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 310, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/akinator/imagen/Akinatorlogo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInsertarLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertarLenguajeActionPerformed
        enviar(CampoNuevoLenguaje.getText());
    }//GEN-LAST:event_BotonInsertarLenguajeActionPerformed

    private void BotonResSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResSIActionPerformed
        enviar("si");
    }//GEN-LAST:event_BotonResSIActionPerformed

    private void BotonResPSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResPSIActionPerformed
        enviar("n");
    }//GEN-LAST:event_BotonResPSIActionPerformed

    private void BotonResNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResNSActionPerformed
        enviar("n");
    }//GEN-LAST:event_BotonResNSActionPerformed

    private void BotonResPNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResPNOActionPerformed
        enviar("n");
    }//GEN-LAST:event_BotonResPNOActionPerformed

    private void BotonResNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResNOActionPerformed
        enviar("no");
    }//GEN-LAST:event_BotonResNOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInsertarLenguaje;
    private javax.swing.JButton BotonResNO;
    private javax.swing.JButton BotonResNS;
    private javax.swing.JButton BotonResPNO;
    private javax.swing.JButton BotonResPSI;
    private javax.swing.JButton BotonResSI;
    private javax.swing.JTextField CampoNuevoLenguaje;
    private javax.swing.JTextField CampoPreguntas;
    private javax.swing.JTextField CampoVarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
