%Sustituciones

sustitucion([el,la,los,las]).
sustitucion([un,uno,una,unas]).
sustitucion([su,sus]).
sustitucion([mi,mis]).

sustitucion([hombre,mujer,hombres,mujeres]).
sustitucion([cuchillo,cuchillos,sierra,sierras]).
sustitucion([juan,maria,irene,hector]).
sustitucion([manzana,manzanas,platano,platanos]).
sustitucion([gato,gatos,cebra,cebras]).
sustitucion([raton,rata,ratones,ratas]).
sustitucion([alumno,alumna,alumnos,alumnas]).
sustitucion([universidad,universidades,colegio,colegios]).
sustitucion([tenedor,tenedores,cuchara,cucharas]).
sustitucion([practica,practicas,trabajo,trabajos]).
sustitucion([canario,canarios,paloma,palomas]).
sustitucion([vuelo,vuelos,travesia,travesias]).
sustitucion([reflejo,reflejos,velocidades,velocidad]).
sustitucion([esperanza,esperanzas,deseo,deseos]).
sustitucion([vida,vidas,entusiasmo,entusiasmos]).
sustitucion([nino,ninos,nina,ninas]).
sustitucion([lugar,lugares,zona,zonas]).
sustitucion([nacimiento,nacimientos,salida,salidas]).
sustitucion([profesor,profesora,profesores,profesoras]).
sustitucion([procesador,procesadores,procesadora,procesadoras]).
sustitucion([texto,textos,documento,documentos,redaccion,redacciones]).
sustitucion([herramienta,herramientas,utensilio,utensilios]).
sustitucion([patata,patatas,tomate,tomates]).
sustitucion([cafe,cafes,agua,aguas,cerveza,cervezas]).
sustitucion([manzano,manzanos,palmera,palmeras]).
sustitucion([mesa,mesas,taburete,taburetes]).
sustitucion([pantalon,pantalones,corbata,corbatas]).

sustitucion([ama,aman,amamos,amo]).
sustitucion([come,comen,comemos,como]).
sustitucion([estudia,estudian,estudiamos,estudio]).
sustitucion([era,eran,eramos]).
sustitucion([cazo,cazaron,cazamos]).
sustitucion([hace,hacen,hacemos,hago]).
sustitucion([canta,cantan,cantamos,canto]).
sustitucion([alzo,alzaron,alzamos,alce]).
sustitucion([esta,estan,estamos,estoy]).
sustitucion([es,son,somos,soy]).
sustitucion([habla,hablan,hablamos,hablo]).
sustitucion([depende,dependen,dependemos,dependo]).
sustitucion([vi,vimos,vieron]).
sustitucion([sirve,sirven,servimos,sirvo]).
sustitucion([recoge,recogen,recogemos,recojo]).
sustitucion([toma,toman,tomamos,tomo]).
sustitucion([compre,compraron,compraron,compro]).
sustitucion([bebe,beben,bebemos,bebo]).
sustitucion([salta,saltan,saltamos,salto]).
sustitucion([sonrie,sonrien,sonreimos,sonrio]).

sustitucion([rojo,rojos,roja,rojas]).
sustitucion([negro,negros,negra,negras]).
sustitucion([grande,grandes]).
sustitucion([blanco,blancos,blanca,blancas]).
sustitucion([gris,grises]).
sustitucion([pequeno,pequena,pequenos,pequenas]).
sustitucion([lento,lenta,lentos,lentas]).
sustitucion([delicado,delicada,delicados,delicadas]).
sustitucion([potente,potentes]).
sustitucion([moreno,morena,morenos,morenas]).
sustitucion([alto,alta,altos,altas]).
sustitucion([frito,fritos,frita,fritas]).
sustitucion([alegre,alegres]).

sustitucion([ella,el,ellas,ellos,yo,nosotros,nosotras]).